# Use root/example as user/password credentials
version: '3.1'

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: root
    networks:
      - mysql-phpmyadmin
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin