# Use root/example as user/password credentials
version: '3.1'

networks:
  backend-net:

volumes:
  db_data:
  mongo_data:
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: root
    networks:
      - backend-net
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend-net
  mongodb: 
    image: mongo 
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-net
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - backend-net
    depends_on:
      - mongodb